modules/application/models/Application.php
<?php

namespace app\modules\application\models;

use Yii;
use app\modules\application\models\ApplicationTypes;
use app\modules\application\models\ApplicationFiles;
use app\modules\application\models\ApplicationAssignment;
use app\modules\application\models\ApplicationCommends;
use app\modules\organization\models\Organization;
use app\modules\user\models\User;
use yii\helpers\Url;

/**
 * This is the model class for table "application".
 *
 * @property integer $id
 * @property integer $application_type
 * @property integer $author
 * @property integer $active
 * @property string $description
 * @property string $date_created
 * @property string $date_plane_end
 * @property string $date_end
 * @property string $coords
 * @property integer $seriosness
 * @property integer $status
 * @property string $address
 * @property string $applicant_name
 * @property string $applicant_phone
 * @property string $applicant_addr
 */
class Application extends \yii\db\ActiveRecord
{
    
    public $image_load; // Переменная для загрузки фотографий
    public $main_category;
    public $statusName;
    public $date_created_human;
    public $date_end_human;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'application';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['application_type', 'author', 'description', 'date_created', 'date_plane_end', 'coords'], 'required'],
            [['application_type', 'author', 'active', 'seriosness', 'status'], 'integer'],
            [['date_created', 'date_plane_end', 'date_end', 'last_updated'], 'safe'],
            [['description'], 'string', 'max' => 5000],
            [['coords', 'applicant_name', 'applicant_phone'], 'string', 'max' => 500],
            [['address'], 'string', 'max' => 1000],
            [['applicant_addr'], 'string', 'max' => 1500],
            [['image_load', 'main_category', 'uncomplete_reason'], 'safe'],
            [['image_load'], 'required', 'on'=>'user-create'],
            [['image_load'], 'required', 'on'=>'api-create']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'application_type' => Yii::t('app', 'Категория заявки'),
            'author' => Yii::t('app', 'Автор'),
            'authorName' => Yii::t('app', 'Автор'),
            'active' => Yii::t('app', 'Активна?'),
            'description' => Yii::t('app', 'Описание'),
            'date_created' => Yii::t('app', 'Дата создания'),
            'date_plane_end' => Yii::t('app', 'Дата планируемого завершения'),
            'date_end' => Yii::t('app', 'Дата завершения'),
            'coords' => Yii::t('app', 'Координаты'),
            'seriosness' => Yii::t('app', 'Важность'),
            'status' => Yii::t('app', 'Статус'),
            'address' => Yii::t('app', 'Адрес'),
            'applicant_name' => Yii::t('app', 'Заявитель - имя'),
            'applicant_phone' => Yii::t('app', 'Заявитель - телефон'),
            'applicant_addr' => Yii::t('app', 'Заявитель - адрес'),
            'fulltype' => Yii::t('app', 'Категория'),
            'statusName' => Yii::t('app', 'Статус'),
            'date_created_human' => Yii::t('app', 'Дата создания'),
            'organizationNames' => Yii::t('app', 'Исполнители'),
            'image_load' => Yii::t('app', 'Изображение'),
            'link' => Yii::t('app', 'Ссылка'),
            'uncomplete_reason' => Yii::t('app', 'Причина неисполнения'),
        ];
    }
    
    public function getImageBefore() {
		
		$model = ApplicationFiles::find()->where(['=', 'application_id', $this->id])->andWhere(['=', 'type', '1'])->one();
		if($model) return $model->src;
		if(!$model) return "/images/style/no-image.png";
	}
    
    public function getImageAfter() {
		
		$model = ApplicationFiles::find()->where(['=', 'application_id', $this->id])->andWhere(['=', 'type', '2'])->one();
		if($model) return $model->src;
		if(!$model) return "/images/style/no-image.png";
	}
	
	public function getFulltype() {
		return $this->type->name . " / " . $this->subtype->name;
	}
	
	public function getType() {
		return ApplicationTypes::findOne(['id'=>$this->subtype->parent_id]);
	}
	
	public function getAuthorModel() {
		return User::findOne(['id'=>$this->author]);
	}
	
	public function getAuthorName() {
		$model = User::findOne(['id'=>$this->author]);
		
		if($organization = $model->organization) {
			return $organization->name;
		}
		
		if(Yii::$app->user->can('admin') || Yii::$app->user->can('moderator')) return $model->fullname;
		return $model->hiddenName;
	}
	
	public function getSubtype() {
		return ApplicationTypes::findOne(['id'=>$this->application_type]);		
	}
	
	public function getStatusName() {
		return $this->statusName;
	}
	
	public function getOrganizations() {
		return Organization::find()->innerJoin('application_assignment as', 'as.organization_id = organization.id')
									->innerJoin('application app', "app.id = as.application_id")->where("app.id = {$this->id}")->all();
	}
	
	public function getOrganizationNames() {
		$arr = [];
		foreach($this->organizations as $org) {
			 $arr[] = $org->name;
		}
		return implode($arr, ",");
	}
	
	public function getCommendsRaw() {
		foreach($this->getCommends() as $commend) {			
			if($commend->author->isOrganizationUser()) $raw_commend .= $commend->author->organization->name . ":" . $commend->text ."\n";			
		}
		return $raw_commend;
	}
	
	public function getLink() {
		return \yii\helpers\Html::a("<i class='glyphicon glyphicon-eye-open'/>", \yii\helpers\Url::to('/workplace/default/view?id='.$this->id, true) );
	}
	
	//remove
	public function getAssignments() {
		return ApplicationAssignment::find()->where(['=', 'application_id', $this->id])->all();
	}
	
	public function getAppAss_rel() {
		return $this->hasMany(ApplicationAssignment::className, ['application_id'=>'id']);
	}
	
	//remove
	public function getCommends() {
		return ApplicationCommends::find()->where(['=', 'application_id', $this->id])->orderBy(['date'=>SORT_DESC])->all();
	}
	
	public function convertTime() {
		
	}
	
	
	public function update_address() {
		$this->address = self::decode_geo($this->coords);
		$this->save();
	}
	
	public static function decode_geo($lat_long) {
		$lat_long = explode(',', $lat_long);
		$sql = "SELECT id FROM gis_areas WHERE ST_CONTAINS(geometry, GeomFromText('POINT({$lat_long[1]} $lat_long[0])', 4294967294)) LIMIT 1";
		$result = Yii::$app->db->createCommand($sql)->queryAll();
		if($result) return $result[0]['id'];
		return "Не определено";
	}

	public function notifyOperators() {
        $operators = User::findByRole('moderator', true);
        Yii::$app->mailer->compose()
            ->setTo($operators)
            ->setFrom([Yii::$app->params['siteEmail'] => Yii::$app->params['siteName']])
            ->setSubject(Yii::t('app', 'Заявка №{1} создана на сайте {0}', [Url::to(["/"], true), $this->id]))
            ->setHtmlBody(Yii::t('app', "Посмотреть статус заявки можно по ссылке <a href='{0}'>{0}</a>", [Url::to(["/workplace/moderator/view?id=/".$this->id], true)]))
            ->send();
    }

    public function notifyExecutors() {
        $users = [];
        $emails = [];
        foreach ($this->assignments as $asg) {
            $users = array_merge($users, $asg->organization->users);
        }
        foreach ($users as $user) {
            $emails[] = $user->email;
        }
        if($emails) {
            Yii::$app->mailer->compose()
                ->setTo($emails)
                ->setFrom([Yii::$app->params['siteEmail'] => Yii::$app->params['siteName']])
                ->setSubject(Yii::t('app', 'Вашей организации была адресована заявка №{1} {0}', [Url::to(["/"], true), $this->id]))
                ->setHtmlBody(Yii::t('app', "Посмотреть заявку можно в личном кабинете <a href='{0}'>{0}</a>", [Url::to(["/workplace/organization/view?id=".$this->id], true)]))
                ->send();
//            https://tselin.kz/workplace/organization/view?id=363
        }

    }
	
	public function afterFind() {
		$this->statusName = Yii::$app->params['application']['status'][$this->status];
		
		$origin_date_created = $this->date_created;
		$origin_date_end = $this->date_end;
		$this->date_created = \Yii::$app->formatter->asDate($this->date_created, 'php:d.m.Y H:i:s');
		$this->date_plane_end = \Yii::$app->formatter->asDate($this->date_plane_end, 'php:d.m.Y H:i:s');
		$this->date_end = \Yii::$app->formatter->asDate($this->date_end, 'php:d.m.Y H:i:s');
		$this->date_created_human = $this->convert_to_human($origin_date_created);
		$this->date_end_human = $this->convert_to_human($origin_date_end);	
		
	}
	
	public function beforeSave($insert) {
		$date = new \DateTime('now', new \DateTimeZone('Asia/Aqtau')); // Текущая дата
		$this->last_updated = $date->format('Y-m-d H:i:s');
		if (parent::beforeSave($insert)) {	        
			$this->address = self::decode_geo($this->coords);
			
			$origin_date_created = $this->date_created;
			$origin_date_end = $this->date_end;
			$this->date_created = \Yii::$app->formatter->asDate($this->date_created, 'php:Y-m-d H:i:s');
			$this->date_plane_end = \Yii::$app->formatter->asDate($this->date_plane_end, 'php:Y-m-d H:i:s');
			$this->date_end = \Yii::$app->formatter->asDate($this->date_end, 'php:Y-m-d H:i:s');
			
	        return true;
	    }
	    return false;
	}
	
	public function afterSave($insert, $changedAttributes){
	    parent::afterSave($insert, $changedAttributes);
	 	
	    /*После сохранения заявки обновить ApplicationAssignment - дату*/	    
	    foreach($this->assignments as $assignment) {
			$assignment->application_end = $this->date_plane_end;
			$assignment->save();
		}
		
		// Если это новая запись, отправить на почту уведомление
        if($insert && $this->scenario !== 'api-create') {
            Yii::$app->user->identity->message(

modules/application/controllers/DefaultController.php
<?php

namespace app\modules\application\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use kujiorpamm\cropit\widgets\CropitWidget;
use yii\data\ActiveDataProvider;

use app\modules\application\models\Application;
use app\modules\application\models\ApplicationTypes;
use app\modules\application\models\ApplicationAssignment;
use app\modules\application\models\ApplicationCommends;
use app\modules\application\models\ApplicationFiles;
use app\modules\organization\models\Organization;

/**
 * Default controller for the `application` module
 */
class DefaultController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['new-application'],
                        'allow' => true,
                        'roles' => ['user', 'admin'],
                    ],
                    [
                        'actions' => ['view'],
                        'allow' => true
                    ],
                    
                ],
            ]
        ];
    }
    
    
    /*Создание заявки обычным пользователем*/
    public function actionNewApplication()
    {
        $model = new Application();
        $model->scenario = 'user-create';
		
		$model->date_created = date('Y-m-d H:i:s');
		$model->date_plane_end = date('Y-m-d H:i:s', strtotime(Yii::$app->params['application']['days_to_add']));
		$model->author = Yii::$app->user->id;
		$model->applicant_name = Yii::$app->user->identity->fname . " " . Yii::$app->user->identity->lname;
		$model->applicant_phone = Yii::$app->user->identity->phone;
		$model->active = 1;
		$model->status = 1;
		
		if($model->load(Yii::$app->request->post())) {
			if($model->save()) {
				
				if($model->image_load) {
					$filename = "images/applications/" . $model->id . ".png";
					CropitWidget::saveAs($model->image_load, $filename);
					$file = new ApplicationFiles;
					$file->type = 1;
					$file->ext = 'png';
					$file->src = "/".$filename;
					$file->application_id = $model->id;
					$file->save();
				}
				
				return $this->redirect("/me");
			}
		}
		
		$allowed_items = ApplicationTypes::find()->select('name_ru')->indexBy('id')->where(['=', 'parent_id', 1])->column();
		return $this->render('new-application', ['model'=>$model, 'category_items'=>$allowed_items]);
        
        return $this->render('index');
    }
    
    public function actionView($id) {
		$model = Application::findOne(['id'=>$id]);
		
		if($model->status == 1) return $this->render('waiting', ['model'=>$model]);
		
		return $this->render('view', ['model'=>$model]);
	}
}

modules/application/views/default/index.php
<div class="application-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

modules/application/views/default/new-application.php
<?php
	$this->title = $model->id;
	/*$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Рабочий стол'), 'url' => ['/workplace']];*/
	/*$this->params['breadcrumbs'][] = Yii::t('app', 'Новая заявка');*/
?>

<?php
	use yii\bootstrap\ActiveForm;
	use yii\bootstrap\Html;
	use kartik\datetime\DateTimePicker;

	use kujiorpamm\cropit\widgets\CropitWidget;
	widgets\mapbox\MapboxWidget::widget(['page'=>'report']);
	$canAdmin = Yii::$app->user->identity->canAdmin();
?>

<?php $form = ActiveForm::begin(['id'=>'app_form']); ?>

<div class="page-index">
	<div class="wrap">
		<div class="container">

			<h2><?=Yii::t('app', 'Новая заявка')?></h2>

			<div class="row">
			<!--ЛЕВАЯ КОЛОНКА-->
			<div class="col-md-6 col-sm-8 col-xs-12">
				<div class="form-splitter"><?=Yii::t('app', 'Общие данные')?></div>
				<div>
					<!--Подкатегория-->
					<div>
						<?=$form->field($model, 'application_type')->dropDownList($category_items, ['prompt'=>'Выберите категорию'])->label(false)?>
					</div>

					<!--Описание-->
					<div class="form-group">
						<!--<label><?=Yii::t('app', 'Текст заявки')?></label>-->
						<?=$form->field($model, 'description')->textArea(['placeholder'=>Yii::t('app', 'Текст заявки')])->label(false)?>
					</div>
				</div>


				<div class="form-splitter"><?=Yii::t('app', 'Фотография')?> <span class="note glyphicon glyphicon-question-sign"><div>Фотография 800x600 </div></span></div>
				<div class="image-loader">
					<?= $form->field($model, 'image_load')->widget(\kujiorpamm\cropit\widgets\CropitWidget::className(), [
						'pluginOptions' => [
							'width' => 400,
							'height' => 300,
							'smallImage' => 'stretch',
							'exportZoom' => 2
					]])->label(false);?>
				</div>

			</div>
			<!--КОНЕЦ ЛЕВАЯ КОЛОНКА-->

			<!--ПРАВАЯ КОЛОНКА-->
			<div class="col-md-6 col-sm-4 col-xs-12">

				<div class="form-splitter"><label for="Application[coords]"><?=Yii::t('app', 'Координаты')?></label></div>
				<div class="same-height">
					<!--Метка на карте-->
					<div>
						<?=$form->field($model, 'coords')->hiddenInput()->label(false)?>
					</div>

					<div class="map" id="map" style="height:400px;">

					</div>
				</div>

			</div>
			<!--КОНЕЦ ПРАВАЯ КОЛОНКА-->


		</div>

		<div class="clearfix">
			<div class="pull-right">
				<button type="submit" class="btn btn-lg btn-success"> <?=Yii::t('app', 'Отправить заявку')?> </button>
			</div>
		</div>

		<?php ActiveForm::end(); ?>

		</div>
	</div>
</div>

modules/application/views/default/projects.php
<?php

?>

modules/application/views/default/view.php
<?php
	use yii\bootstrap\ActiveForm;
	use yii\bootstrap\Html;
	use kartik\date\DatePicker;

	use kujiorpamm\cropit\widgets\CropitWidget;
	use app\modules\application\assets\ApplicationCreateAsset;
	use app\modules\application\controllers\ApplicationController;

	ApplicationCreateAsset::register($this);

	$this->title = $model->id;
	$this->params['breadcrumbs'][] = Yii::t('app', 'Заявка №{0}', [$model->id]);

	if(Yii::$app->user->isGuest) {
		$canAdmin = false;
	} else {
		$canAdmin = Yii::$app->user->identity->canAdmin();
	}



?>

<script>
	var is_view = true;
	var app_coords = [<?=$model->coords?>];
</script>

<div class="page-index">
	<div class="wrap">
		<div class="container">

			<div class="application-view">
				<div class="view-block-container application-info white">
					<div class="heading">
						<div class="clearfix">
							<div class="pull-left"> <?=Yii::t('app', 'Заявка №{0} от {1}, планируемое завершение: {2}', [$model->id, substr($model->date_created, 0, 10), substr($model->date_plane_end, 0, 10)])?></div>
							<div class="pull-right status">
								<?=Yii::t('app', 'Статус:')?> <?=$model->statusName?>
								<?php if($model->status == 3) echo " {$model->date_end}"?>
							</div>
						</div>
					</div>
					<div class="content">
						<div class="row">
							<div class="col-sm-8">
								<div class="type"><?=$model->fulltype?></div>
								<div class="text"><?=$model->description?></div>
								<div class="orgs">
									<!--НАЧАЛО НАЗНАЧЕННЫЕ ИСПОЛНИТЕЛИ-->
									<?=Yii::t('app', 'Назначенные исполнители: ')?>
									<?php
										if($organizations = $model->organizations) {
											foreach($organizations as $org) {
												echo "<a href='/organization/default/view?id={$org->id}'>$org->name</a> ";
											}
										} else {
											echo Yii::t('app', 'Пока нет...');
										}

									?>
									<!--КОНЕЦ НАЗНАЧЕННЫЕ ИСПОЛНИТЕЛИ-->
								</div>
								<div class="author">
									<?=Yii::t('app', 'Автор обращения: ') . "<span>" . $model->authorName?> </span> <br/>
								</div>


							</div>
							<div class="col-sm-4">
								<div class="image">
									<img class="img img-responsive img-popup" src="<?=$model->imageBefore?>"/>
								</div>
							</div>
						</div>
					</div>



				</div>

				<div class="row">
					<div class="col-sm-8">

						<!--НАЧАЛО КОММЕНТАРИИ-->
						<div class="commends-block">
							<h3><?=Yii::t('app', 'Комментарии')?></h3>
							<?php

								if($commends = $model->commends) {
									foreach($model->commends as $cmd) {
										echo ApplicationController::render_commend($cmd);
									}
								} else {
									echo "<div class='empty'>".Yii::t('app', 'Пока нет...')."</div>";
								}


							?>
						</div>

						<?php if(Yii::$app->user->identity && Yii::$app->user->identity->canCommendApplication($model->id)):?>
							<div class="note"><?=Yii::t('app', 'Чтобы оставить комментарий, откройте заявку через <a class="red" href="/workplace/default/view?id={0}">рабочий стол</a>', [$model->id])?></div>
						<?php endif; ?>
						<!--КОНЕЦ КОММЕНТАРИИ-->

					</div>
					<div class="col-sm-4">

						<!--НАЧАЛО КАРТА-->
						<div id="ymap_view" class="view-block-container view-block-container application-view-map map"></div>
						<!--КОНЕЦ КАРТА-->

						<!--НАЧАЛО ОРГАНИЗАЦИИ-->
						<div class="view-block-container white executors">
							<div class="heading"><?=Yii::t('app', 'Исполнители')?></div>
							<table class="table no-borders">
								<?php
									if($organizations = $model->assignments) {
										foreach($organizations as $org) {

											if($canAdmin) {
												echo "<tr>
														<td>{$org->organization->name} <span>{$org->contract->name}</span></td>
														<td><a class='confirm-link' href='/workplace/moderator/unasign-organization?id={$model->id}&org={$org->organization->id}'><span class='glyphicon glyphicon-remove'></span></a></td>
													</tr>";
											} else {
												echo "<tr>
														<td>{$org->organization->name} <span>{$org->contract->name}</span></td>
														<td></td>
													</tr>";
											}


										}
									} else {
										echo Yii::t('app', 'Пока нет...');
									}

								?>
							</table>
						</div>
						<!--КОНЕЦ ОРГАНИЗАЦИИ-->


					</div>
				</div>

			</div>

		</div>
	</div>
</div>

modules/application/views/default/waiting.php
<?php
	use yii\bootstrap\ActiveForm;
	use yii\bootstrap\Html;
	use kartik\date\DatePicker;

	use kujiorpamm\cropit\widgets\CropitWidget;
	use app\modules\application\assets\ApplicationCreateAsset;
	use app\modules\application\controllers\ApplicationController;

	ApplicationCreateAsset::register($this);

	$this->title = $model->id;
	$this->params['breadcrumbs'][] = Yii::t('app', 'Заявка №{0}', [$model->id]);

	if(Yii::$app->user->identity) {
		$canAdmin = (Yii::$app->user->identity && Yii::$app->user->identity->canAdmin());
	} else {
		$canAdmin = false;
	}



?>

<script>
	var is_view = true;
	var app_coords = [<?=$model->coords?>];
</script>

<div class="page-index">
	<div class="wrap">
		<div class="container">

			<center><?=Yii::t('app', 'Заявка ожидает модерации')?></center>

		</div>
	</div>
</div>